cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: /Users/willian.costa/Documents/Spring/upload-dir
security:
  jwt:
    token:
      secret-key: 53cce37
      expire-length: 3600000
spring:
  application:
    name: primeiro_projeto_API

  profiles:
    active: dev

  jpa:
    open-in-view: false

  servlet:
    multipart:
      enable: true
      file-size-threshold: 2kb
      max-file-size: 200mb
      max-request-size: 215mb